DROP TABLE IF EXISTS TBL_EMPLOYEES;
 
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  date_of_birth DATE NOT NULL,
  gender VARCHAR(10) NOT NULL,
  country VARCHAR(100) DEFAULT NULL,
  expired BIT DEFAULT 1,
  attachments VARCHAR(2000),
  attach BLOB
);

DROP TABLE IF EXISTS TBL_EXPENSES;

CREATE TABLE TBL_EXPENSES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  exp_type VARCHAR(100) NOT NULL,
  cust_type VARCHAR(100) NOT NULL,
  purpose VARCHAR(100) NOT NULL,
  vend_name VARCHAR(100) NOT NULL,
  inv_date DATE NOT NULL,
  inv_no VARCHAR(100) NOT NULL,
  inv_amt DECIMAL(15,2),
  sanc_amt DECIMAL(15,2),
  clm_amt DECIMAL(15,2),
  remarks VARCHAR(1000) DEFAULT NULL,
  attachments VARCHAR(2000),
  attach BLOB
);